local_backend: true

backend:
  name: github
  repo: Trisigma-Official/status
  branch: main
  base_url: https://auth-status.trisigma.io

media_folder: static/img
public_folder: /img

collections:
  - name: issues
    label: Issues
    label_singular: Issue
    folder: content/issues
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Resolved, name: resolved, widget: boolean, default: false }
      - label: Resolved At
        name: resolvedWhen
        widget: datetime
        required: false
      - label: Severity
        name: severity
        widget: select
        options:
          - notice
          - disrupted
          - down
          - monitoring
      - label: Affected Systems
        name: affected
        widget: select
        multiple: true
        options:
          - { label: "[Enterprise] Splitter", value: "Splitter" }
          - { label: "[Enterprise] Configurator", value: "Configurator" }
          - { label: "[Enterprise] Compute", value: "Compute" }
          - { label: "[Essential] API estimate", value: "API estimate" }
          - { label: "[Essential] API console", value: "API console" }
          - { label: "[Essential] Web UI", value: "Web UI" }
          - { label: "[Essential] /api/v1/config.json", value: "/api/v1/config.json" }
          - { label: "[Essential] /api/v1/geo", value: "/api/v1/geo" }
      - label: Section
        name: section
        widget: hidden
        default: issue
      - { label: Body, name: body, widget: markdown }
